version: '3.8'

services:
  mock-api:
    build: ./app
    container_name: mock-api
    restart: always
    ports:
      - "8080:80"
      - "9700:9700"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/success"]  
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      load_test:
        ipv4_address: 192.168.1.100

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./volume/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - load_test

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-volume-1:/var/lib/grafana
    networks:
      - load_test

volumes:
  grafana-volume-1:
  influxdb-data:

networks:
  load_test:
    external: true
